# Generated by Django 4.2.5 on 2023-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction_amount_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='call_type',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('long', 'Long')], max_length=10, null=True),
        ),
    ]
