# Generated by Django 4.2.5 on 2023-11-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
