# Generated by Django 4.2.5 on 2023-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
